# https://github.com/bitnami/charts/tree/master/bitnami/mongodb/#installing-the-chart
architecture: replicaset

pdb:
  create: true

metrics:
  enabled: true
  serviceMonitor:
    # we need to add the prometheus CRD for this to work
    enabled: false
